name: Build and Push Docker image

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: false

env:
  IMAGE_NAME: eromero1907/pokeneas
  TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # (Opcional) Si quieres multi-arquitectura, agrega setup-qemu y platforms abajo.
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}
          # Para AWS/EC2 (x86_64) normalmente basta amd64.
          # platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
